require: rubocop-rails

AllCops:
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 20

Naming/PredicateName:
  Enabled: false

# Style/ClassAndModuleChildren:
  # EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

# Style/SymbolArray:
  # EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
