default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 1 } %>
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>

development:
  <<: *default
  database: correct_certificate_development

test:
  <<: *default
  database: correct_certificate_test
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>

production:
  <<: *default
  database: correct_certificate_production
