:concurrency: 5
development:
  :concurrency: 1
production:
  :concurrency: 1
:queues:
  - default
:scheduler:
  :schedule:
    certificate_verification:
      every: 30s
      class: CertificateVerificationJob
      queue: default
