# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby

name: Ruby CI

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3
          yarn install

      - name: Setup database
        env:
          DATABASE_URL: postgres://postgres@localhost
        run: |
          rails db:create RAILS_ENV=test
          rails db:schema:load RAILS_ENV=test

      - name: Run tests
        run: bundle exec rspec

      - name: Run rubocop
        run: bundle exec rubocop
